title: "Zachary Roberts | Portfolio"
remote_theme: "jekyll/minima"
minima:
  skin: dark
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-redirect-from
header_pages:
  - index.md
  - projects.md

external_links:
  - title: "Ordinary Engineering"
    url: "https://ordinaryengineering.com/"
